all: congreso-sabado.mp4 congreso-viernes(mañana).mp4 causalidad-encuentro3.mp4

congreso-sabado.mp4:
	wget https://github.com/glandfried/videos/releases/download/bayes.2023.2/congreso-sabado.zip
	unzip congreso-sabado.zip

congreso-viernes(mañana).mp4:
	wget https://github.com/glandfried/videos/releases/download/bayes.2023.2/congreso-viernes.manana.zip
	unzip congreso-viernes.manana.zip

causalidad-encuentro3.mp4:
	wget https://github.com/glandfried/videos/releases/download/bayes.2023.2/causalidad-encuentro3-11septiembre.zip
	unzip causalidad-encuentro3-11septiembre.zip
