all: unidad1.mp4 unidad2.mp4 unidad3-parte1.mp4

unidad1.mp4:
	wget https://github.com/glandfried/videos/releases/download/bayes.2024.2/unidad1.mp4

unidad2.mp4:
	wget https://github.com/glandfried/videos/releases/download/bayes.2024.2/unidad2.mp4

unidad3-parte1.mp4:
	wget https://github.com/glandfried/videos/releases/download/bayes.2024.2/unidad3-parte1.mp4
